get_footprints:
	#easyeda2kicad --overwrite --lcsc_id C119084 --full
	easyeda2kicad --overwrite --lcsc_id C44212 --full
	# https://www.lcsc.com/product-detail/Signal-Relays_HF-Xiamen-Hongfa-Electroacoustic-HFD4-12-SR_C44212.html

